call pathogen#infect()
set nocompatible
syntax enable
colorscheme peachpuff " `zellner` also not bad
set encoding=utf-8
set showcmd " Display <leader> in the ruler --doesn't appear to be working?
            " Display incomplete commands --according to Mislav (http://mislav.uniqpath.com/2011/12/vim-revisited/)
filetype plugin indent on

" if has('gui_running')
" 	set background=light
" else
" 	set background=dark
" endif
"set background=dark
"colorscheme solarized

"" Whitespace & wrapping
set tabstop=2 shiftwidth=2
"set expandtab 							" Use spaces, not tabs
set number 									" Show line numbers in Terminal
set wrap linebreak nolist 	" Enable Vimcast's soft wrapping

set mouse=a 								" Jump to a subject in :help via mouse click

"" Searching
set hlsearch 		" highlight matches
set incsearch 	" incremental searching
set ignorecase 	" searches are case insensitive...
set smartcase 	" ... unless they contain at least one capital letter
